name: CI Anita

on:
  push:
    branches: ["CI/CD-Anita"]
  pull_request:
    branches: ["main"]

jobs:
  test-quality-analysis:
    name: Build • Test • Quality Check
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: https://sonarcloud.io

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Give permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Compile project
        run: ./gradlew clean build -x test

      - name: Execute unit tests
        run: ./gradlew test

      - name: Run Checkstyle analysis
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Save test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-report
          path: build/test-results/test

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test

      - name: Check SonarCloud Quality Gate
        if: ${{ env.SONAR_TOKEN != '' && env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != '' }}
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}